### ISSUE TITLE
question for the seqID classes

### ISSUE THREAD

**Issue by k821209** [mourisl/centrifuger#17]
hello, 

Thank you for your valuable publication. I recently ran the Centrifuger and found our read matching showing just "genus" or "phylum" etc. as seqID. The other seqIDs showed recognizable NCBI IDs and had no problems. However, the indications of "genus" or "phylum" are confusing. Can you explain what this is indicating? I ran against the index file of GTDB you shared. 

Best regards, 

YJ

**Comment by mourisl** [comment]
This happens when the read can be classified to multiple sequences (strains) with the same score. In this case, Centrifuger will reduce the results to the common ancestors in the phylogeny tree. You can use the option "-k" to control how much entries in the output for reach read. By default, -k=1, so the report is the lowest common ancestor, which is the behavior of Kraken2. Hope this helps.

**Comment by k821209** [comment]
thank you for your explanation. 👍
