### ISSUE TITLE
How to achieve strain level classification

### ISSUE THREAD

**Issue by zwh82** [mourisl/centrifuger#18]
From `centrifuger` paper, I found it can perform strain level profiling. How to achieve it? Is this achieved by assigning the `seqID` column in the `classification.tsv` file to the corresponding strain? 
In addition, compared with `centrifuge`, it does not seem to output the report file. If I want to get the relative abundance of a taxa, can I only count the taxa's reads and calculate the relative abundance?

Best regards,
Wenhai

**Comment by mourisl** [comment]
The strain level classification depends on the read itself. If a read can be uniquely classified to a strain, it will be a strain-level classification in the classification output file. However, in many cases, it is hard to uniquely align a read to a strain, especially for short reads. You can check whether the seqID is the sequence name instead of terms like "species/genus/...". 

This is perfect timing for asking about the report file! I recently implemented the "centrifuger-quant" program for Centrifuger that will use the EM algorithm to estimate the abundances (more information in README) and generate a report file in the same format as Centrifuge's. I just pushed that to the github repo, and you may pull the current version for a test. For better abundance estimation, you may consider running centrifuger with higher number "-k", so the classification can be more specific (though more ambiguous).

**Comment by zwh82** [comment]
I found that the report file does not provide strain abundance. I know that strains can be determined from `seqID` when k=1. This means that I can only manually estimate the relative abundance of strains according to the classification file. This will be achieved by calculating the base number of covered strains and normalizing by genome length. However, this approach would prevent the use of `centrifuger-quant`'s EM algorithm for read reassignment and abundance estimation.
Is there a way to provide the strain abundance?

**Comment by mourisl** [comment]
The report file should contain the strain information if you see that in the classification result. I tested it on the example data, and got the ~50% abundance for the two Legionella strains. They maybe labeled as "subspecies" instead of "strain", depending on how it is defined in the nodes.dmp file when building the taxonomy tree. If the report still misses the strain you are interested in (the name column should also indicative of the strain), is it possible to share the classification file and the ".2" and ".3" file of the index if you are using a customized database? Thank you!

**Comment by mourisl** [comment]
Yes, if lowest taxid ID is at species level, the report can only reach species level. In that case, you may need to use the count based on the seqid information in the classification file. The "seqid' is actually even at a lower level than strain level. For example, if you include human genome in the index, the seqID could be the chromosome ID. For strains has both genome and plasmid sequence in the database, the seqID could also corresponds the plasmid.

Right, you may need to create tax IDs to distinguish strains.
